### ISSUE TITLE
unclear if all calls need to be authenticated

### ISSUE THREAD

**Issue by tcurdt** [ahmdrz/goinsta#117]
It's not really clear from the docs whether calls to
```
insta.Profiles.ByName(username)
insta.NewHashtag(tag)
```
really need to be authenticated via `Login` or not.

**Comment by themester** [comment]
I don't thought about the fact that some user does make request without being logged previously.
All request that are done with sendSimpleRequest function can be done without being logged.

I will add to the documentation tomorrow. Thanks for your report.

As I see you can interact with Hashtag without login.
https://github.com/ahmdrz/goinsta/blob/master/hashtags.go#L55

**Comment by themester** [comment]
@tcurdt Okay. In this case you must be logged in. This week I am going to review all package and I am going to add in documentation if call can be done without being logged.

**Comment by tcurdt** [comment]
Yes, I just tried `insta.Profiles.ByName(username)` without `Login` but that gave
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1272aad]

goroutine 1 [running]:

foo/vendor/gopkg.in/ahmdrz/goinsta%2ev2.(*Instagram).sendRequest(0xc4200b22c0, 0xc4201247a8, 0x0, 0x0, 0x0, 0x0, 0x0)
  vendor/gopkg.in/ahmdrz/goinsta.v2/request.go:80 +0x62d

foo/vendor/gopkg.in/ahmdrz/goinsta%2ev2.(*Instagram).sendSimpleRequest(0xc4200b22c0, 0x13ae18e, 0x16, 0xc420058850, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
  vendor/gopkg.in/ahmdrz/goinsta.v2/request.go:29 +0xac

foo/vendor/gopkg.in/ahmdrz/goinsta%2ev2.(*Profiles).ByName(0xc42000e180, 0x13a8e72, 0x6, 0x0, 0x46, 0x2d)
  vendor/gopkg.in/ahmdrz/goinsta.v2/profiles.go:22 +0xd0

foo/actions.(*Gather).Run(0xc420125f70, 0x13, 0x7ffeefbff6b3)
```

**Comment by themester** [comment]
Yes. Updated your repo with `go get` I fixed the error. See https://github.com/ahmdrz/goinsta/commit/110f862ced1dd8b2029d2c79940b9d13dd1321c6

**Comment by tcurdt** [comment]
Thanks, but now the `Sync` fails even when logged in.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x1295d8e]

goroutine 1 [running]:

foo/vendor/github.com/ahmdrz/goinsta.(*Instagram).sendRequest(0x0, 0xc42059ea28, 0x0, 0x0, 0x0, 0x0, 0x0)
  foo/src/foo/vendor/github.com/ahmdrz/goinsta/request.go:79 +0x82e

foo/vendor/github.com/ahmdrz/goinsta.(*Instagram).sendSimpleRequest(0x0, 0x13d51dd, 0xe, 0xc42059eae8, 0x1, 0x1, 0x8, 0x0, 0xc420135638, 0x1360ac0, ...)
  foo/src/foo/vendor/github.com/ahmdrz/goinsta/request.go:31 +0xac

foo/vendor/github.com/ahmdrz/goinsta.(*User).Sync(0xc42059f870, 0xc42059ece0, 0xc42059edc0)
  foo/src/foo/vendor/github.com/ahmdrz/goinsta/users.go:163 +0xbf

foo/actions.(*Gather).Run(0xc4205a1f70, 0x13ed988, 0xc4200c82c0)
  foo/src/foo/actions/gather.go:79 +0x640

main.main()
  foo/src/foo/main.go:34 +0x20d

exit status 2
```

**Comment by themester** [comment]
Yes. This is because you are creating User. To get User object use Profiles.ByID() or Profiles.ByName

**Comment by tcurdt** [comment]
I am getting the users like this
```
  tags := []string{"foo"}
  for _, tag := range tags {
    hashtag := insta.NewHashtag(tag)

    for page := 0; page < 1 && hashtag.Next(); page++ {

      for _, section := range hashtag.Sections {
        for _, media := range section.LayoutContent.Medias {
          item := media.Item
          user := item.User
          users[user.Username] = user
        }
      }
    }
  }
```
and those users fail to `Sync`. Users from `Profiles.ByName` work OK.
Not sure I understand the difference of the two.

**Comment by themester** [comment]
Oh okay. Let me a minute
